# Change of Basis - Solved Examples

In this demonstration, we'll take a look at how to perform change of basis calculations in python. Mainly we'll look at
- how to denote the basis vectors in numpy
- how to create the transformation matrix
- how to perform change of basis

In [5]:
#Import the libraries
import numpy as np

A few conventions before we proceed
- By default, we'll assume the original basis as B1 and the new basis as B2
- The original vector representation is denoted as v1 and the new vector representation as v2
- Matrix M is to be multiplied with v1 to obtain v2

#### Case 1 - Moving from the standard basis to a non-standard basis

In this scenario, you are given a point's representation in the standard basis.Your task is to identify the same point's representation in a new set of basis vectors

**Q** - Let's say you're given a point P which is represented as v1 in the standard basis B1 as shown below

\begin{equation*} v_1 = \begin{bmatrix} 4 \\ 9 \end{bmatrix}\space in \space B_1 = \begin{bmatrix} 1 &0 \\ 0 &1 \end{bmatrix}  \end{equation*} 

Now you need to find the same point's representation in a different basis B2, which is denoted as follows

\begin{equation*}B_2 = \begin{bmatrix} 1 \\ 2\end{bmatrix} \space and \space \begin{bmatrix} 1 \\ 3\end{bmatrix}\end{equation*} 

\begin{equation*}or \space B_2 = \begin{bmatrix} 1 & 1 \\ 2 & 3\end{bmatrix}\end{equation*} 

\begin{equation*}v_2 = \begin{bmatrix} 3 \\  1\end{bmatrix} \end{equation*}

In [7]:
#Step - 1 
#Denoting the new basis vectors as numpy arrays
#Notice the way the arguments are taken

B2 = np.array([[1,1],[2,3]])
B2

array([[1, 1],
       [2, 3]])

In [ ]:
B2 = np.array([arguments])

As you can see, numpy creates the matrix by taking in the rows as the arguments. So therefore, first create the basis vector matrix and then pass the arguments.

In [1]:
#Step - 2
#Create the transformation matrix M

Now we know that


\begin{equation*} M = B_2^{-1}* B_1\end{equation*} 


Since B1 is the standard basis vectors which is also the identity matrix, the above equation gets simplified as

\begin{equation*} M = B_2^{-1}\end{equation*} 

In [8]:
# M is the inverse of B2
M = np.linalg.inv(B2)

In [9]:
M

array([[ 3., -1.],
       [-2.,  1.]])

In [10]:
M @ B2

array([[1., 0.],
       [0., 1.]])

In [11]:
#Step - 3 
#Perform the change of basis

We know that, in order to get v2 we have the equation as 

\begin{equation*} v_2 = M*v_1\end{equation*} 

In [13]:
#Denote v1
v1 = np.array([[4],[9]])

In [14]:
v1

array([[4],
       [9]])

In [15]:
#Apply the change of basis formula
#Multiply the transformation matrix M with v1

v2 = M @ v1

In [16]:
v2

array([[3.],
       [1.]])

So, therefore the same point P's representation in the new basis vectors B2, is given as 

\begin{equation*} v_2 = \begin{bmatrix} 3 \\ 1\end{bmatrix}\end{equation*} 

#### Case 2 - Moving from a non-standard basis to the standard basis

In this scenario, you are given a point's representation in a non-standard basis.Your task is to identify the same point's representation in the standard basis vectors

Let's take the same example as above in the reverse order

**Q** - Let's say you're given a point P which is represented as v1 in the non-standard basis B1 as shown below

\begin{equation*} v_1 = \begin{bmatrix} 3\\ 1 \end{bmatrix}\space in \space B_1 = \begin{bmatrix} 1 &1 \\ 2 &3 \end{bmatrix}  \end{equation*} 

Now you need to find the same point's representation in the standard basis B2, which is denoted as follows

\begin{equation*}B_2 = \begin{bmatrix} 1 \\ 0\end{bmatrix} \space and \space \begin{bmatrix} 0 \\ 1\end{bmatrix}\end{equation*} 

\begin{equation*}or \space B_2 = \begin{bmatrix} 1 & 0 \\ 0 & 1\end{bmatrix}\end{equation*} 

Recall the formula for transformation matrix M again

\begin{equation*} M = B_2^{-1}* B_1\end{equation*} 

In this case B2 is the standard basis or the identity matrix and therefore it's inverse will be B2 itself. Therefore the above equation gets simplified as 

\begin{equation*} M = B_1\end{equation*} 

In [25]:
#Step-1 
#Denote B1 as numpy arrays
B1 = np.array([[1,1],[2,3]])

In [26]:
#Step-2
#Find the transformation matrix M
M = B1

In [27]:
M

array([[1, 1],
       [2, 3]])

In [28]:
#Step -3 
#Apply the change of basis formula
#v2 = M*v1
v1 = np.array([[3],[1]])
v2 = M @ v1
v2

array([[4],
       [9]])

### Summary

The same point P can have multiple representations in multiple basis vectors. When moving between two set of basis vectors the following rule holds true

\begin{equation*} B_1*v_1 = B_2*v_2\end{equation*} 

B1 is one set of basis vectors and v1 is the point's representation in B1 whereas B2 is another set of basis vectors and v2 is the same point's representation in B2.

In the above example, we have shown that

\begin{equation*}  \begin{bmatrix} 1 & 0 \\ 0 & 1\end{bmatrix}* \begin{bmatrix} 4 \\ 9 \end{bmatrix} = \begin{bmatrix} 1 & 1 \\ 2 & 3\end{bmatrix}*\begin{bmatrix} 3 \\ 1\end{bmatrix}\end{equation*} 

or in more concrete terms

\begin{equation*} 4* \begin{bmatrix} 1  \\ 0 \end{bmatrix} + 9 * \begin{bmatrix} 0 \\ 1\end{bmatrix} = 3* \begin{bmatrix} 1 \\ 2\end{bmatrix} + 1*\begin{bmatrix} 1 \\ 3\end{bmatrix}\end{equation*} 

The above representation is shown in the diagram below

![Change of Basis](images\COB2.png)

**Shortcut for finding M**

Once we've correctly set the conventions and when our movement is between standard and non-standard basis vectors, it's possible to express M in terms of just the non-standard basis vectors

- If we're moving from a standard basis to a non-standard basis, M is equal to the inverse of the non-standard basis vectors

- If we're moving from a non-standard basis to a standard basis, M is equal to the non-standard basis vectors.